// Whitelist of Kaspa x402 services the router will proxy to, with each service's USD price
// (the gateways are USD-priced, floored at 0.5 KAS). Client calls /call?service=<id>&<params>.
// Whitelisted (not arbitrary URLs) to avoid SSRF and to only front our own services.
export const SERVICES = {
  exposure: { url: "https://kaspa-402-exposure.kaspadev.workers.dev/exact", usd: 0.10 }, // ?address=kaspa:...
  cluster: { url: "https://kaspa-402-cluster.kaspadev.workers.dev/exact", usd: 0.15 }, // ?address=kaspa:...
  ghost: { url: "https://kaspa-402-ghost.kaspadev.workers.dev/exact", usd: 0.10 }, // ?target=kaspa:... | txid
  ask: { url: "https://kaspa-402-ask.kaspadev.workers.dev/exact", usd: 0.03 }, // ?q=...
  research: { url: "https://kaspa-402-research.kaspadev.workers.dev/exact", usd: 0.10 }, // ?asset=krc20:NACHO
  redteam: { url: "https://kaspa-402-redteam.kaspadev.workers.dev/exact", usd: 0.20 }, // ?scriptHex=...
  reserve: { url: "https://kaspa-402-reserve.kaspadev.workers.dev/exact", usd: 0.15 }, // ?covenantAddress=kaspa:...
};

export const DEFAULT_USD = 0.2; // fallback price for an unrecognized service id
