// Whitelist of Kaspa x402 services the facilitator will proxy to.
// Client calls  /call?service=<id>&<passthrough params>  → facilitator pays this gateway in KAS.
// Whitelisted (not arbitrary URLs) to avoid SSRF and to only front our own services.
export const SERVICES = {
  exposure: "https://kaspa-402-exposure.kaspadev.workers.dev/exact", // ?address=kaspa:...
  cluster: "https://kaspa-402-cluster.kaspadev.workers.dev/exact", // ?address=kaspa:...
  ghost: "https://kaspa-402-ghost.kaspadev.workers.dev/exact", // ?target=kaspa:... | txid
  ask: "https://kaspa-402-ask.kaspadev.workers.dev/exact", // ?q=...
  research: "https://kaspa-402-research.kaspadev.workers.dev/exact", // ?asset=krc20:NACHO
  redteam: "https://kaspa-402-redteam.kaspadev.workers.dev/exact", // ?scriptHex=...
  reserve: "https://kaspa-402-reserve.kaspadev.workers.dev/exact", // ?covenantAddress=kaspa:...
};
